env:
  browser: true
  es2021: true
  node: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - "@typescript-eslint"
rules:
  accessor-pairs: error
  array-bracket-newline: error
  array-bracket-spacing: error
  array-callback-return: error
  array-element-newline:
    - error
    - ArrayExpression: consistent
  arrow-body-style: error
  arrow-parens: error
  arrow-spacing: error
  block-scoped-var: error
  block-spacing: error
  brace-style: error
  callback-return: error
  camelcase: warn
  capitalized-comments:
    - error
    - never
  class-methods-use-this: error
  comma-dangle: error
  comma-spacing: error
  comma-style: error
  complexity: error
  computed-property-spacing: error
  consistent-return: error
  consistent-this:
    - error
    - self
  curly: error
  default-case: error
  default-case-last: error
  default-param-last: error
  dot-location:
    - error
    - property
  dot-notation: error
  eol-last: error
  eqeqeq: error
  for-direction: error
  func-call-spacing: error
  func-name-matching: error
  func-names: error
  func-style:
    - error
    - declaration
    - allowArrowFunctions: true
  function-call-argument-newline:
    - error
    - consistent
  function-paren-newline: error
  generator-star-spacing: error
  getter-return: error
  global-require: 0
  grouped-accessor-pairs: error
  guard-for-in: error
  handle-callback-err: error
  id-match:
    - warn
    - "^[a-zA-Z_][a-zA-Z0-9]*$|^[A-Z][A-Z_]+$"
    - ignoreDestructuring: true
  implicit-arrow-linebreak: error
  indent: error
  init-declarations: error
  jsx-quotes: error
  key-spacing: error
  keyword-spacing: error
  line-comment-position: error
  linebreak-style: error
  lines-around-comment: error
  lines-around-directive: error
  lines-between-class-members: error
  max-classes-per-file:
    - error
    - 4
  max-depth: error
  max-len: error
  max-lines:
    - error
    - max: 600
  max-lines-per-function:
    - error
    - max: 200
  max-nested-callbacks: error
  max-params:
    - warn
    - max: 4
  max-statements:
    - error
    - max: 40
  max-statements-per-line: error
  multiline-comment-style: error
  multiline-ternary: error
  new-cap: warn
  new-parens: error
  newline-after-var: error
  newline-before-return: error
  newline-per-chained-call: error
  no-alert: error
  no-array-constructor: error
  no-async-promise-executor: error
  no-await-in-loop: error
  no-bitwise: error
  no-buffer-constructor: error
  no-caller: error
  no-catch-shadow: error
  no-cond-assign: error
  no-confusing-arrow: error
  no-constant-condition: error
  no-control-regex: error
  no-constructor-return: error
  no-debugger: error
  no-div-regex: error
  no-dupe-args: error
  no-dupe-else-if: error
  no-dupe-keys: error
  no-duplicate-case: error
  no-duplicate-imports: error
  no-else-return: error
  no-empty: warn
  no-empty-character-class: error
  no-empty-function: 0
  no-eq-null: error
  no-eval: error
  no-ex-assign: error
  no-extend-native: error
  no-extra-bind: error
  no-extra-boolean-cast: error
  no-extra-label: error
  no-extra-semi: error
  no-floating-decimal: error
  no-func-assign: error
  no-implicit-coercion: error
  no-implicit-globals: error
  no-implied-eval: error
  no-import-assign: error
  no-inline-comments: error
  no-invalid-regexp: error
  no-invalid-this: error
  no-iterator: error
  no-label-var: error
  no-labels: error
  no-lone-blocks: error
  no-lonely-if: error
  no-loop-func: error
  no-loss-of-precision: error
  no-mixed-operators: error
  no-mixed-requires: error
  no-multi-assign: error
  no-multi-spaces: error
  no-multi-str: error
  no-multiple-empty-lines: error
  no-native-reassign: error
  no-negated-condition: error
  no-negated-in-lhs: error
  no-nested-ternary: error
  no-new: error
  no-new-func: error
  no-new-object: error
  no-new-require: error
  no-new-wrappers: error
  no-obj-calls: error
  no-octal-escape: error
  no-param-reassign: error
  no-path-concat: error
  no-process-env: error
  no-process-exit: error
  no-promise-executor-return: error
  no-proto: error
  no-restricted-exports: error
  no-restricted-globals: error
  no-restricted-imports: error
  no-restricted-modules: error
  no-restricted-properties: error
  no-restricted-syntax: error
  no-return-assign: error
  no-return-await: error
  no-script-url: error
  no-self-compare: error
  no-sequences: error
  no-shadow: 0
  no-spaced-func: error
  no-sync: 0
  no-tabs: error
  no-template-curly-in-string: error
  no-throw-literal: error
  no-trailing-spaces:
    - error
    - ignoreComments: true
  no-undef-init: error
  no-undefined: error
  no-underscore-dangle:
    - error
    - allowAfterThis: true
  no-unmodified-loop-condition: error
  no-unneeded-ternary: error
  no-unreachable-loop: error
  no-unused-expressions: 0
  no-use-before-define: 0
  no-useless-backreference: error
  no-useless-call: error
  no-useless-computed-key: error
  no-useless-concat: error
  no-useless-constructor: error
  no-useless-rename: error
  no-useless-return: error
  no-var: error
  no-void: error
  no-whitespace-before-property: error
  nonblock-statement-body-position: error
  object-curly-newline: error
  object-curly-spacing: error
  object-property-newline: error
  object-shorthand: error
  one-var:
    - error
    - never
  one-var-declaration-per-line: error
  operator-assignment: error
  operator-linebreak:
    - error
    - before
  padded-blocks: error
  padding-line-between-statements: error
  prefer-arrow-callback: error
  prefer-const: error
  prefer-destructuring: 0
  prefer-exponentiation-operator: error
  prefer-named-capture-group: warn
  prefer-numeric-literals: error
  prefer-object-spread: error
  prefer-promise-reject-errors: error
  prefer-regex-literals: error
  prefer-rest-params: error
  prefer-spread: error
  prefer-template: error
  quote-props:
    - error
    - consistent-as-needed
  quotes: error
  radix: error
  require-atomic-updates: error
  require-await: warn
  require-unicode-regexp: error
  rest-spread-spacing: error
  semi: error
  semi-spacing: error
  semi-style: error
  sort-imports: error
  sort-vars: error
  space-before-blocks: error
  space-before-function-paren: error
  space-in-parens: error
  space-infix-ops: error
  space-unary-ops: error
  spaced-comment: error
  strict: error
  switch-colon-spacing: error
  symbol-description: error
  template-curly-spacing: error
  template-tag-spacing: error
  unicode-bom: error
  vars-on-top: error
  wrap-iife: error
  wrap-regex: error
  yield-star-spacing: error
  yoda: error
  "@typescript-eslint/no-var-requires": "off"
  "@typescript-eslint/no-empty-function": warn
  "@typescript-eslint/no-this-alias": 0
  "@typescript-eslint/no-explicit-any": error
